---

- hosts: all
  become: yes
  vars_files:
    - vars/secrets.yml
    - vars/common.yml
  roles:
    - { role: elasticsearch, tags: ["elasticsearch"], when: inventory_hostname == 'elastic_host_01' }
    - { role: kibana,        tags: ["kibana"],        when: inventory_hostname == 'kibana_host_01'  }
    - { role: logstash,      tags: ["logstash"],      when: inventory_hostname == 'logstash_host_01'}
