---
- name: Copy docker-compose.yml file to server
  template:
    src: docker-compose.yml.j2
    dest: /tmp/docker-compose.yml
    mode: u=rw,g=r,o=r

- include_tasks: docker-prerequisites.yml

- name: Start elasticSearch stack
  docker_compose:
    project_src: /tmp